### ISSUE TITLE
Creating a .torrent file

### ISSUE THREAD

**Issue by Arturbarth** [bashkirtsevich-llc/mad-torrent#2]
Can i create a .torrent file with MadTorrent?
I Need to create a new torrentfile like uTorrent (File » Create Torrent File). 
Its possible with MadTorrent?

**Comment by bashkirtsevich** [comment]
No. This lib works only as a client, but its possible to extend for creating torrent files. Its very easy logic, but now I'm not using Delphi.
You can use the code from this library for reading necessary files as single stream, then pass the data to sha1 function for pieces generation. To convert the data to the .torrent file you can use the Bencode-encoder from this library.
